[versions]
kotlinx = "1.6.4"
spring-boot = "3.0.2"
spring-kafka = "2.9.5"
junit = "5.9.2"
kotest = "5.5.4"
kotest-spring = "1.1.2"
kluent = "1.72"
mockito = "4.1.0"
wiremock = "2.35.0"
testcontainers = "1.17.6"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx" }
spring-boot = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka-test", version.ref = "spring-kafka" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
junit = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property-jvm = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest" }
kotest-framework-api-jvm = { module = "io.kotest:kotest-framework-api-jvm", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotest-spring" }
wiremock = { module = "com.github.tomakehurst:wiremock-jre8", version.ref = "wiremock" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
testcontainers-couchbase = { module = "org.testcontainers:couchbase", version.ref = "testcontainers" }
